# Generated by Django 4.0.4 on 2022-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='views_server/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
