# Generated by Django 4.0.4 on 2022-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics/'),
        ),
    ]
