# Generated by Django 4.0.4 on 2022-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
