# Generated by Django 4.0.4 on 2022-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='car_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
