# Generated by Django 4.0.4 on 2022-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_phone_number_alter_post_car_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='car_price',
            field=models.CharField(default='Not available', max_length=250),
        ),
    ]
